# Use the official Python image
FROM python:3.9

# Set working directory
WORKDIR /usr/src/app

# Install any necessary dependencies (if required)
# COPY requirements.txt ./
# RUN pip install --no-cache-dir -r requirements.txt

# Default command to run Python script
CMD ["python", "script.py"]
